---
- hosts: main
  become: yes
  vars_files:
    - Users/privvars.yml
    
  tasks: 
    
    - name: Install curl
      apt: 
        name: curl
        state: present
        update_cache: yes
        
    - name: Enable UFW
      community.general.ufw:
        state: enabled
        
    - name: Allow TCP 80
      community.general.ufw:
        rule: allow
        port: '80'
        proto: tcp
        
    - name: Allow TCP 8888
      community.general.ufw:
        rule: allow
        port: '8888'
        proto: tcp
        
    - name: Allow TCP 1467
      community.general.ufw:
        rule: allow
        port: '1467'
        proto: tcp
    
    - name: Change SSH port
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#Port 22'
        line: 'Port 1467'
    
    - name: Allow key SSH auth
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#PubkeyAuthentication yes'
        line: 'PubkeyAuthentication yes'
     
    - name: Add User1
      ansible.builtin.user:
        name: "{{ users[0] }}"
        generate_ssh_key: yes
        
    - name: Add User2
      ansible.builtin.user:
        name: "{{ users[1] }}"
        generate_ssh_key: yes
        
    - name: Add User3
      ansible.builtin.user:
        name: "{{ users[2] }}"
        generate_ssh_key: yes
    
    - name: Add Key to User1
      ansible.posix.authorized_key:
        user: "{{ users[0] }}"
        state: present
        key: "{{ publickey }}"
        
    - name: Add Key to User2
      ansible.posix.authorized_key:
        user: "{{ users[1] }}"
        state: present
        key: "{{ publickey }}"
        
    - name: Add Key to User3
      ansible.posix.authorized_key:
        user: "{{ users[2] }}"
        state: present
        key: "{{ publickey }}"
      
